### ISSUE TITLE
Subscription connection issue when Kapacitor docker set with custom hostname

### ISSUE THREAD

**Issue by danyli78** [influxdata/influxdata-docker#117]
How to replicate:

Using the latest 1.3.1 image version

```
- name: Create Kapacitor Container
  become: yes
  docker_container:
    name: kapacitor
    image: "{{ image_name }}"
    hostname: "kapacitor-dev"  <===
    networks:
      - name: influxdata
    restart_policy: always
    state: started
    published_ports: "9092:9092"
    exposed_ports: "9092/tcp"
    log_driver: journald
    volumes:
      - /etc/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - /kapacitor:/var/lib/kapacitor
  notify:
    - wait for port status
```
Error message in InfluxDB container:
```
[I] 2017-07-28T17:10:25Z Post http://kapacitor-dev:9092/write?consistency=&db=investopedia&precision=ns&rp=default: dial tcp: lookup kapacitor-dev on 127.0.0.11:53: no such host service=subscriber
```

When I remove the "hostname" in my ansible config and deploy, subscription works fine, no connection refuse error.

All containers (telegraf, influxdb, kapacitor) are on the same host.  Telegraf and Influxdb communicate fine using the same "networks: influxdata" and custom hostname.
