### ISSUE TITLE
How to set influxdb subscription and retention policy for kapacitor

### ISSUE THREAD

**Issue by tomaszgawlik** [influxdata/influxdata-docker#129]
Hi,
I'm trying to move all my custom configuration from the configuration file to environment variables. 
Missing the last thing, originally in my config file: 

```
[[influxdb]]
  ...
  [influxdb.subscriptions]
    prod = [ "last_week_realtime" ]
```

which I've tried to convert: 

```
kapacitor:
        image: kapacitor:1.3
        environment:
            - KAPACITOR_INFLUXDB_0_INFLUXDB.SUBSCRIPTIONS_PROD_0=last_week_realtime
```
I've tried few other variations but my current output is that kapacitor is creating subscriptions for all databases and policies. 
I'd appreciate some help with this, is it even possible to set?
