### ISSUE TITLE
Auth in chronograf doesn't work

### ISSUE THREAD

**Issue by Punkoivan** [influxdata/influxdata-docker#159]
Hello! Using the next compose file:
```
version: '2'
services:
 influx:
  image: influxdb:1.3
  environment:
   INFLUXDB_ADMIN_PASSWORD: pass
   INFLUXDB_ADMIN_USER: god
   INFLUXDB_DB: telegraf
   INFLUXDB_HTTP_AUTH_ENABLED: true
   INFLUXDB_HTTP_BIND_ADDRESS: :8086
   INFLUXDB_USER: telegraf
   INFLUXDB_USER_PASSWORD: tel
  volumes:
   - core-influx:/var/lib/influxdb
  ports:
   - 8086:8086/tcp
 kapacitor:
  image: kapacitor:1.3.3
  environment:
   KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
   KAPACITOR_HOSTNAME: kapacitor
   stdin_open: true
   tty: true
  links:
   - influx:inlfuxdb
  ports:
   - 9092:9092/tcp
 chronograf:
  image: chronograf:1.3.8
  environment:
   INFLUXDB_URL: http://influxdb:8086
   KAPACITOR_URL: http://kapacitor:9092
   INFLUXDB_USERNAME: god
   INFLUXDB_PASSWORD: pass
   stdin_open: true
   tty: true
  links:
   - influx:influxdb
   - kapacitor:kapacitor
  ports:
   - 8888:8888/tcp
```

After start-up we go to chronograf URL and see no auth and able to do anything we want. And obviously not only we but anybody.

I checked env vars in influx container -
INFLUXDB_HTTP_AUTH_ENABLED = true

What I'm doing wrong and how I can fix it?

Thanks,
Punko Ivan
