### ISSUE TITLE
How to run influxdb docker image with other user other than root?

### ISSUE THREAD

**Issue by ping2nomula** [influxdata/influxdata-docker#188]
I have mount path with other than root permissions which i want to use it for influxdb data dir.
But i am facing permission problems when i start docker. 
Is there a way to change influxdb process permissions?

**Comment by jsternberg** [comment]
You can always start the container with a user other than root by using the `-u` flag. It should be in the [docker documentation](https://docs.docker.com/engine/reference/commandline/run/#options).

We don't have any docs on this because it's not really a telegraf thing, but a "how you want to run your containers" thing which is a docker thing.

**Comment by cailloumajor** [comment]
@jsternberg when launching the container with `-u` flag, initialization done in `init-influxdb.sh` fails due to missing write permissions.
So, IMHO, this issue is still valid and not only depends on "how you want to run your containers".

**Comment by HarrPerson** [comment]
@cailloumajor should work for mounted volume with correct permissions. For example:
Docker Compose example:
```yaml
version: "2"
services:
  influxdb:
    image: influxdb
    user: "1234:1234"
    ports:
      - 8086:8086
    volumes:
      - /path/to/influxdb:/var/lib/influxdb
```
Permission on `/path/to/influxdb`:
`drwx------  1234  1234 /path/to/influxdb`
