### ISSUE TITLE
init-influxdb.sh - influxdb init process failed.

### ISSUE THREAD

**Issue by idanshm** [influxdata/influxdata-docker#191]
The influxdb fails to start after recreating the pod.
It seems as it cannot recover the data.

I am using AWS EFS as mount point.
Any suggestions how it can be solved?

[I] 2018-02-12T14:05:05Z InfluxDB starting, version 1.4.3, branch 1.4, commit 60d27e6995558f38a39e90b35a92cbac080310a3
[I] 2018-02-12T14:05:05Z Go version go1.9.2, GOMAXPROCS set to 4
[I] 2018-02-12T14:05:05Z Using configuration at: /etc/influxdb/influxdb.conf
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process in progress...
influxdb init process failed.

**Comment by idanshm** [comment]
More info:
root@influxdb-3445006706-m9rkr:/# influx -host 127.0.0.1 -port 8086 -execute "SHOW DATABASES"                                                                                                                     
Failed to connect to http://127.0.0.1:8086: Get http://127.0.0.1:8086/ping: dial tcp 127.0.0.1:8086: getsockopt: connection refused
Please check your connection settings and ensure 'influxd' is running.

**Comment by originsmike** [comment]
I just saw this too. In my case, I had an .iql script (which gets auto-executed on startup) sitting around that had some `CREATE CONTINUOUS QUERY` and `CREATE RETENTION POLICY` lines that presumably fail if they already exist in the database.

It would be really nice if the default logging level had more information than "failed".

**Comment by QuinnBast** [comment]
I also ran into this... I had initially mounted an `.iql` file, but after removing the `.iql` file, the problem still persists. It seems like that was not the cause of the problems. The extremely vague messaging is kinda problematic, no clue how to figure out what is wrong.

For me this is happening in the `influxdb:1.8.2` docker image.

2018 to 2023, still an issue and the logging looks the exact same :sob: 

For me, the issue ended up being something in the `config` section of the [influx helm chart here](https://github.com/influxdata/helm-charts/blob/influxdb-4.10.1/charts/influxdb/values.yaml#L233). I removed this config section and influx start to work as expected. In the helm chart, the `config` section generates [this ConfigMap](https://github.com/influxdata/helm-charts/blob/influxdb-4.10.1/charts/influxdb/templates/configmap.yaml), which gets mounted in as `influxdb.conf`, so my best guess for anyone who is also having this issues is: Something in your `influxdb.conf` file is wrong. Though good luck figuring out what it is.

I had copied an `influx.conf` file from a previous influx deployment into these configuration settings for the helm chart but it seems like the configuration settings I specified were causing influx init to fail even though these same configuration settings were being used in another production influx instance on the same docker image outside of Kubernetes with a volume mount...

Not that it is helpful to anyone here 5 years later, but this was the config I was attempting to use in the helm chart that caused the error:

```yaml
config:
  reporting_disabled: false
  rpc: {}
  meta:
    dir: "/var/lib/influxdb/meta"
    retention-autocreate: true
    logging-enabled: true
  data:
    dir: "/var/lib/influxdb/data"
    index-version: "inmem"
    wal-dir: "/var/lib/influxdb/wal"
    wal-fsync-delay: "0s"
    validate-keys: false
    query-log-enabled: true
    cache-max-memory-size: 1073741824
    cache-snapshot-memory-size: 26214400
    cache-snapshot-write-cold-duration: "10m0s"
    compact-full-write-cold-duration: "4h0m0s"
    compact-throughput: 50331648
    compact-throughput-burst: 50331648
    max-series-per-database: 1000000
    max-values-per-tag: 100000
    max-concurrent-compactions: 0
    max-index-log-file-size: 1048576
    series-id-set-cache-size: 100
    trace-logging-enabled: false
    tsm-use-madv-willneed: false
  coordinator:
    write-timeout: "10s"
    max-concurrent-queries: 0
    query-timeout: "0s"
    log-queries-after: "0s"
    max-select-point: 0
    max-select-series: 0
    max-select-buckets: 0
  retention:
    enabled: true
    check-interval: "30m0s"
  shard_precreation:
    enabled: true
    check-interval: "10m0s"
    advance-period: "30m0s"
  monitor:
    store-enabled: true
    store-database: "_internal"
    store-interval: "10s"
  http:
    enabled: true
    bind-address: ":8086"
    auth-enabled: true
    log-enabled: true
    suppress-write-log: false
    write-tracing: false
    flux-enabled: true
    flux-log-enabled: true
    pprof-enabled: true
    pprof-auth-enabled: false
    debug-pprof-enabled: false
    ping-auth-enabled: false
    https-enabled: false
    https-certificate: "/etc/ssl/influxdb.pem"
    https-private-key: ""
    max-row-limit: 0
    max-connection-limit: 0
    shared-secret: ""
    realm: "InfluxDB"
    unix-socket-enabled: false
    unix-socket-permissions: "0777"
    bind-socket: "/var/run/influxdb.sock"
    max-body-size: 25000000
    access-log-path: ""
    max-concurrent-write-limit: 0
    max-enqueued-write-limit: 0
    enqueued-write-timeout: 30000000000
  logging:
    format: "auto"
    level: "info"
    suppress-logo: false
  subscriber:
    enabled: true
    http-timeout: "30s"
    insecure-skip-verify: false
    ca-certs: ""
    write-concurrency: 40
    write-buffer-size: 1000
  graphite:
    enabled: false
  collectd:
    enabled: false
  opentsdb:
    enabled: false
  udp:
    enabled: false
  continuous_queries:
    log-enabled: true
    enabled: true
    query-stats-enabled: false
    run-interval: "1s"
  tls:
    min-version: ""
    max-version: ""
```
