### ISSUE TITLE
Where is the influxdb's  query log file in the docker pod? 

### ISSUE THREAD

**Issue by M233** [influxdata/influxdata-docker#225]
I can't find it in the "/var/log/influxdb" folder. This folder is empty .
The influxdb's configuration is default .
Docker image is  influxdb:1.5

**Comment by jsternberg** [comment]
I think you can just use `docker logs`. The default logging output should be to stdout in the docker container.

**Comment by vadi2** [comment]
That works!

**Comment by pinkynrg** [comment]
it is quite odd that logs can't be easily saved on file.

Trying to tweak the Dockerfile so that a log file can be created.

**Comment by jsternberg** [comment]
Logs can be easily saved to a file. Docker has its own log management infrastructure. If we send logs to standard output, it gives the easiest to configure method of dealing with logs. if we sent the logs to a file inside of the container, it more greatly limits the possibilities of where logs can go.

https://docs.docker.com/config/containers/logging/configure/

I'm going to close this since we aren't going to change how the output is logged. The proper way to log a container's output is to send the logs to standard output and docker manages the logging.

**Comment by pinkynrg** [comment]
on docker-compose.yml file is possible to do the following:

```
influx-client-web:
    image: influxdb:latest
    command: bash -c "influxd 2>&1 | tee -a /var/log/influxdb/influxdb.log"
    volumes:
        - ./logs:/var/log/influxdb
        - influx-web-data:/var/lib/influxdb
    ports:
      - '8086:8086'

```
