### ISSUE TITLE
More than one database creation with env.variables

### ISSUE THREAD

**Issue by lestatk0** [influxdata/influxdata-docker#251]
Could I create more than one database with the help of env.variables.
Ex.: docker run --rm \
      -e INFLUXDB_DB=db0 -\
      -e INFLUXDB_DB=db1
      influxdb /init-influxdb.sh
In this case only the last one will be created, how can I create both of them

**Comment by psreekala** [comment]
Would like to create multiple databases..did this work?

**Comment by lestatk0** [comment]
seems that the question is still opened

**Comment by danieldides** [comment]
The value of `INFLUXDB_DB` is just passed off to this exec command: `INFLUX_CMD="influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -execute "` with the value of `CREATE_DB_QUERY="CREATE DATABASE $INFLUXDB_DB"`, so a quick (hacky) work around to allow you to create multiple databases is to inject additional queries into this command via the environment variable. For instance:

```
version: '3'

services:
  influx:
    image: influxdb:1.6
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: one; CREATE DATABASE two;```
has allowed me to create both a "one" database and a "two" database at container start time.

This is obviously a terrible hack, but it works in a pinch 😉 

The relevant source for these commands I referenced is here: https://github.com/influxdata/influxdata-docker/blob/d76a6a184dec6a82978964882641a743adb76989/influxdb/1.7/init-influxdb.sh#L17

**Comment by zimmertr** [comment]
Hm, this does not appear to be working anymore with the latest image. At least not with this declaration in my Kubernetes deployment manifest:

```
                  env:
                      - name: INFLUXDB_DB
                        value: "telegraf; CREATE DATABASE proxmox; CREATE DATABASE unifi"
```

**Comment by zimmertr** [comment]
Figured out a way actually. With Kubernetes at least. By providing a `lifecycle` policy you can execute a command on the pod after it has been launched. For example:
```
                  lifecycle:
                      postStart:
                          exec:
                              command: ["/bin/sh", "-c", "influx -password '${INFLUXDB_ADMIN_PASSWORD}' -username '${INFLUXDB_ADMIN_USER}' -execute '{{ influxdb_cmds }}'"]
```

Where the `INFLUXDB_ADMIN_PASSWORD` and `INFLUXDB_ADMIN_USER` variables are configured in the `env` section of my Kubernetest manifest and the `influxdb_cmds` variable is injected via Ansible as a jinja template. 

`influxdb_cmds: 'CREATE DATABASE proxmox; CREATE DATABASE unifi'`
