### ISSUE TITLE
Cannot create a regular user

### ISSUE THREAD

**Issue by oxyole** [influxdata/influxdata-docker#294]
In the [docker hub page of influxdb](https://hub.docker.com/_/influxdb/) in section **Database Initialization** it is mentioned, that with variables **INFLUXDB_USER** and **INFLUXDB_USER_PASSWORD** I can create a regular user for the specified **INFLUXDB_DB** database. But this does not work.

My `docker-compose.yml` looks like this:
```yaml
version: "3"
services:
    influxdb:
        container_name: influxdb
        restart: unless-stopped
        image: influxdb
        environment:
            - INFLUXDB_DB=testdb
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_USER=myuser
            - INFLUXDB_USER_PASSWORD=mypass
        ports:
            - "8086:8086"
        volumes:
            - influx-data:/var/lib/influxdb

volumes:
    influx-data:
```
In the log I see, that it does not create the user, but tries to create the database and gets 403, obviously. Eventually, the initialisation fails.

It works fine for the admin user, but I do not want to create a user with full privileges, since I only need to access that particular db.

What am I doing wrong here?
