### ISSUE TITLE
arm32v7 doesn't work on Pi B Rev 2

### ISSUE THREAD

**Issue by timdonovanuk** [influxdata/influxdata-docker#304]
Hi,

On a Raspbery Pi Model B Rev 2 on latest Raspbian Stretch Lite. Using:

``docker run --rm arm32v7/influxdb influxd config > influxdb.conf`` 

just results in an empty influxdb.conf

Using the following docker-compose results in nothing happening:

```
  influxdb:
    container_name: influxdb
    image: arm32v7/influxdb:latest
    volumes:
      - /opt/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=
      - INFLUXDB_USER=test
      - INFLUXDB_USER_PASSWORD=
      - INFLUXDB_DB=test
```

No container log is visible (``docker logs -t -f influxdb``)
