### ISSUE TITLE
Kapacitor data volume mount 

### ISSUE THREAD

**Issue by Menturan** [influxdata/influxdata-docker#315]
This issue is related to issue #56. 

Data from kapacitor didn’t show up at the volume mounting point on the host.
Below is a part of my docker-compose file:
```yaml
influxdb...
chronograf...

kapacitor:
    image: kapacitor:1.5
    container_name: kapacitor
    hostname: kapacitor
    volumes:
      # Data directory
      - /var/metrics/data/kapacitor:/var/lib/kapacitor
      # Configuration
      - /var/metrics/config/kapacitor:/etc/kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      KAPACITOR_LOGGING_FILE: STDOUT
      KAPACITOR_LOGGING_LEVEL: ERROR
    links:
      - influxdb
    depends_on:
      - influxdb
```

After investigating inside the docker container to find out where the kapacitor data were stored I found it at `/root/.kapacitor`. 
I changed the mapping to this folder and the everything works fine.
```yaml
      # Data directory
      - /var/metrics/data/kapacitor:/root/.kapacitor
```
Why isn’t the data stored in `/var/lib/kapacitor`?

Looking at the [config](https://github.com/influxdata/influxdata-docker/blob/master/kapacitor/1.5/kapacitor.conf) that’s being copied in the Dockerfile, it looks fine.
