### ISSUE TITLE
Use Docker Secrets for Credentials

### ISSUE THREAD

**Issue by DransfeldSK** [influxdata/influxdata-docker#328]
Please add an option to read the admin and user passwords from a file.

Using a file's contents allows for integration with Docker Secret Store, which enables deterministic credentials for administration purposes instead of a random password generated at container init, or worse, plaintext passwords within Docker Stack definitions.

Common convention is to use separate ENV variables suffixed with `_FILE` to define the path of files containing the information otherwise passed as plain text ENV variables.

https://github.com/influxdata/influxdata-docker/blob/56529df4a46eaac4a83c87d9f36f3ba328b4676a/influxdb/1.7/init-influxdb.sh#L21

**Comment by rafi0101** [comment]
@Influxdata Any news on this topic?

Maybe this from MariaDB is useful:

```python
# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
	local var="$1"
	local fileVar="${var}_FILE"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		mysql_error "Both $var and $fileVar are set (but are exclusive)"
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	unset "$fileVar"
}
```
https://github.com/MariaDB/mariadb-docker/blob/d7ffe9456c0ac967edca9515a377b08c5bc58309/docker-entrypoint.sh#L21-L40

**Comment by maxi017** [comment]
I would also like to know if there are any plans to implement this in the future.

Did anybody got this working with the snipped linked by @rafi0101 ?

**Comment by EnochPrime** [comment]
@maxi017 I was able to with some trial and error. I used this [article](https://echoicdev.home.blog/2021/12/13/how-to-add-secrets-to-your-docker-containers/) for reference. Make sure the `docker-entrypoint.sh` file is executable and add any other variables you want to be able to use as a secret.

docker-entrypoint.sh
```
#!/bin/bash

set -e

# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
	local var="$1"
	local fileVar="${var}_FILE"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
		exit 1
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	unset "$fileVar"
}

file_env 'DOCKER_INFLUXDB_INIT_PASSWORD'
file_env 'DOCKER_INFLUXDB_INIT_ADMIN_TOKEN'

exec "$@"
```

excerpt of docker compose
```
influxdb:
    image: influxdb:2.1.1
    entrypoint: /docker-entrypoint.sh /entrypoint.sh
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/INFLUXDB_INIT_PASSWORD
      DOCKER_INFLUXDB_INIT_ORG: home
      DOCKER_INFLUXDB_INIT_BUCKET: telegraf
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/INFLUXDB_INIT_ADMIN_TOKEN
    secrets:
      - INFLUXDB_INIT_PASSWORD
      - INFLUXDB_INIT_ADMIN_TOKEN
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    networks:
      - influxdb
    ports:
      - 8086:8086
  ```
