### ISSUE TITLE
Can't bind mount /proc from host to telegraf

### ISSUE THREAD

**Issue by applefreak** [influxdata/influxdata-docker#349]
Hi, I'm running Telegraf inside a Docker container through `docker-compose`.

I want Telegraf to monitor the host, so I need `/proc` in the container.

Here's the relevant `docker-compose.yml` file. 

```
  telegraf:
    image: "telegraf"
    environment:
      HOSTNAME: "monmonmon-telegraf"
      HOST_ETC: "/hostfs/etc"
      HOST_PROC: "/hostfs/proc"
      HOST_SYS: "/hostfs/sys"
      HOST_MOUNT_PREFIX: "/hostfs"
    volumes:
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
    privileged: true 
    depends_on:
      - influxdb
```

But I'm not seeing the host's `/proc/net/dev` (where there's more than 2 interfaces) in `/hostfs/proc/net/dev`. Instead, it's the container's `/proc/net/dev` that resides in `/hostfs/proc/net/dev` (which only have 2 interfaces, `eth0` & `lo`). The `privileged` flag doesn't seem to have any affect.

I guess this is less of a Telegraf issue but Docker's. But maybe someone has experience that could chime in?

Thanks

**Comment by GeorgeMac** [comment]
I'm no expert by any means, so unsure if this will work. But you could try using the `net: host` (perhaps just under your `privileged: true` line). Perhaps something funny is going on because of the network namespaces. I only guess as you're accessing a network related section of the proc filesystem. This will run telegraf in the hosts network namespace. Rather than creating its own namespace + bridge.

**Comment by applefreak** [comment]
Hi there, this works! But I was hoping it could be on it's own bridge since there are other services I want them to be able to resolve each other through service names. Here's my full compose file.

```
version: '3'

services:
  influxdb:
    image: "influxdb:1.7.8-alpine"
    environment:
      HOSTNAME: "monmonmon-influx"
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      # - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089/udp"

  telegraf:
    image: "telegraf"
    environment:
      HOSTNAME: "monmonmon-telegraf"
      HOST_ETC: "/hostfs/etc"
      HOST_PROC: "/hostfs/proc"
      HOST_SYS: "/hostfs/sys"
      HOST_MOUNT_PREFIX: "/hostfs"
    volumes:
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
    privileged: true
    network_mode: "host"
    depends_on:
      - influxdb

  grafana:
    image: "grafana/grafana"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - "3333:3000"

volumes:
  grafana-data:
```

Thanks
