### ISSUE TITLE
Unable to create bolt clientUnable to open boltdb;

### ISSUE THREAD

**Issue by chenliu1993** [influxdata/influxdata-docker#383]
Hi all, 
   i am running chronograf:latest, while this error shows up:
```
time="2020-03-31T16:30:46Z" level=error msg="Unable to create bolt clientUnable to open boltdb; is there a chronograf already running?  invalid argument"
```
Does anyone has idea on this?
Thanks.

**Comment by russorat** [comment]
@chenliu1993 thanks for the issue. BoltDB (which powers Chronograf) can only have one process access it at a time. Most likely, something else is trying to talk to the same boltdb at the same time.

Optionally, chronograf supports an etcd backend as well if you'd like multiple chronografs to read from the same metadata db. https://docs.influxdata.com/chronograf/v1.8/administration/create-high-availability/

**Comment by hyacin75** [comment]
Hello, I am getting this same error -

```
me@manager:/mnt/swarm_files/TIC$ docker service logs TIC_chronograf
TIC_chronograf.1.6mvlo3y8ggnw@FCOS-D1    | time="2020-10-07T20:52:53Z" level=error msg="Unable to create bolt clientUnable to open boltdb; is there a chronograf already running?  invalid argument"
TIC_chronograf.1.j64gsaqwcdkj@FCOS-D1    | time="2020-10-07T20:52:14Z" level=error msg="Unable to create bolt clientUnable to open boltdb; is there a chronograf already running?  invalid argument"
TIC_chronograf.1.3srvhufe2sz8@FCOS-D1    | time="2020-10-07T20:52:27Z" level=error msg="Unable to create bolt clientUnable to open boltdb; is there a chronograf already running?  invalid argument"
TIC_chronograf.1.pnadt22nckfz@FCOS-D1    | time="2020-10-07T20:52:39Z" level=error msg="Unable to create bolt clientUnable to open boltdb; is there a chronograf already running?  invalid argument"
me@manager:/mnt/swarm_files/TIC$
```

There is 100% for sure no other instance of Chronograf running.  I've even cleared out the data directory entirely and started perfectly fresh just to make sure there wasn't a stale lock or something - same error.

I _do_ however, have some funny filesystem stuff going on below that is probably causing it - but I can't tell what it is doing from this error to know exactly what the problem is or how to go about resolving it at the filesystem level.

What I've got, is a CephFS directory on the hypervisors, 9P shared/mounted on the Docker nodes, bind mounted to the containers.  Influx itself runs in this configuration without issue, happily plugging away and updating its databases, but Chronograf won't start at all.

Any insight into exactly what is happening when this error is reported would be greatly appreciated!!

**Comment by russorat** [comment]
Chronograf by default tries to make a boltdb in the same directory where it is run unless you specify the path to the bolt file. I think you should check where the bolt file is trying to be created and ensure chronograf has r/w to that folder.

**Comment by hyacin75** [comment]
> 
> 
> Chronograf by default tries to make a boltdb in the same directory where it is run unless you specify the path to the bolt file. I think you should check where the bolt file is trying to be created and ensure chronograf has r/w to that folder.

When I switch it back to the NFS storage, running on the same server, it starts without issue, and doesn't create any additional files in the only mounted filesystem is has -

```
me@manager:/mnt/container_volumes/TIC/chronograf-data$ ls
backup  chronograf-v1.db
me@manager:/mnt/container_volumes/TIC/chronograf-data$ cd backup/
me@manager:/mnt/container_volumes/TIC/chronograf-data/backup$ ls
chronograf-v1.db.1.8.0  chronograf-v1.db.1.8.4
me@manager:/mnt/container_volumes/TIC/chronograf-data/backup$
```

All the other storage is inside the container, and running on the same server, so there's no change there, just to the volume -

```
  chronograf:
    image: chronograf:alpine
    command: chronograf --influxdb-url=http://influxdb:8086
    hostname: chronograf
    configs:
      - source: timezone
        target: /etc/timezone
    environment:
      - TZ=America/New_York
    deploy:
      placement:
        constraints:
          - node.platform.arch==x86_64
          - node.hostname==FCOS-D1
      labels:
        - "traefik.enable=true"
        - "traefik.port=8888"
        - "traefik.docker.network=swarmnet"
        - "traefik.frontend.rule=Host:chronograf.cntr"
    networks:
      - swarmnet
    volumes:
      - "TIC-chronograf-data:/var/lib/chronograf"
```
```
  TIC-chronograf-data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.55,nolock,soft,rw"
      device: ":/volume1/container_volumes/TIC/chronograf-data"
```

I see nothing in the happy container matching bolt or boltdb -

```
/ # find / -iname "*boltdb*" -print
/ # find / -iname "*bolt*" -print
/ #
```

but it is up and happy when running with the NFS volume -

```
[root@FCOS-D1 core]# docker logs TIC_chronograf.1.lq1ijzgdjtgjk01p6mmnot75b
time="2020-10-08T01:13:08Z" level=info msg="Serving chronograf at http://[::]:8888" component=server
time="2020-10-08T01:13:08Z" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime"
time="2020-10-08T01:13:16Z" level=info msg="Response: OK" component=server method=GET remote_addr="10.0.3.8:48412" response_time="103.397µs" status=200
time="2020-10-08T01:13:27Z" level=info msg="Response: OK" component=server method=GET remote_addr="10.0.3.8:48416" response_time="46.585µs" status=200
time="2020-10-08T01:13:38Z" level=info msg="Response: OK" component=server method=GET remote_addr="10.0.3.8:48424" response_time="62.29µs" status=200
<snip>
```

Still stumped :-(
