### ISSUE TITLE
Automatic upgrade documentation in docker hub doesn't work as described

### ISSUE THREAD

**Issue by chrishoage** [influxdata/influxdata-docker#462]
I tried to follow the upgrade guide in DockerHub, however it doesn't function as described. 

The previous Docker images ran influxdb as root, and thus the `/var/lib/influxdb` data was written as root. It appears that version 2 uses a influx user with a UID of 1000. When running the upgrade influx tries to read the previous data and fails, since it is owned by root 

```json
{"level":"info","ts":1614453291.239362,"caller":"upgrade/upgrade.go:395","msg":"Starting InfluxDB 1.x upgrade"}
{"level":"info","ts":1614453291.2398243,"caller":"upgrade/upgrade.go:409","msg":"No InfluxDB 1.x config file specified, skipping its upgrade"}
{"level":"info","ts":1614453291.2398694,"caller":"upgrade/upgrade.go:412","msg":"Upgrade source paths","meta":"/var/lib/influxdb/meta","data":"/var/lib/influxdb/data"}
{"level":"info","ts":1614453291.2399273,"caller":"upgrade/upgrade.go:413","msg":"Upgrade target paths","bolt":"/var/lib/influxdb2/influxd.bolt","engine":"/var/lib/influxdb2/engine"}
{"level":"info","ts":1614453291.246558,"caller":"bolt/bbolt.go:76","msg":"Resources opened","service":"bolt","path":"/var/lib/influxdb2/influxd.bolt"}
{"level":"info","ts":1614453291.2494872,"caller":"migration/migration.go:153","msg":"Bringing up metadata migrations","service":"migrations","migration_count":14}
{"level":"info","ts":1614453291.6299906,"caller":"upgrade/setup.go:148","msg":"CLI config has been stored.","path":"/etc/influxdb2/influx-configs"}
{"level":"info","ts":1614453291.6302035,"caller":"upgrade/database.go:201","msg":"Checking available disk space"}
{"level":"info","ts":1614453291.6305807,"caller":"upgrade/upgrade.go:461","msg":"Database upgrade error, removing data"}
Error: error getting size of /var/lib/influxdb/data: open /var/lib/influxdb/data/_internal: permission denied
See 'influxd -h' for help
````

My setup isn't particularly complicated, just a single instance of influx with a single dataset for telegraf. 

The upgrade instructions as written do not function. 

Here is my docker-compose section 

```yaml
  influxdb:
    restart: ${RESTART-unless-stopped}
    image: influxdb:1.8.4
    container_name: influxdb
    hostname: influxdb
    ports:
      # Telegraf run on the metal and is the only thing that needs to post to the db
      - 127.0.0.1:8086:8086
    volumes:
      - ${CONFIG_DIR}/influxdb:/var/lib/influxdb
```

Adding the outlined environment variables 

```yaml
  influxdb:
    restart: ${RESTART-unless-stopped}
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    ports:
      # Telegraf run on the metal and is the only thing that needs to post to the db
      - 127.0.0.1:8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ${CONFIG_DIR}/influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=upgrade
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      - DOCKER_INFLUXDB_INIT_RETENTION=25w
volumes:
  influxdb-data:
```

It is also unclear from the documentation alone if `DOCKER_INFLUXDB_INIT_BUCKET` should match the bucket that is being upgraded - or if it should be a unique unused bucket, and if existing buckets will be upgraded.
