### ISSUE TITLE
The config file cannot be mount as read-only

### ISSUE THREAD

**Issue by Henkru** [influxdata/influxdata-docker#468]
The official readme in [Docker Hub](https://hub.docker.com/_/influxdb) describes the config file could be mount as read-only. However, that does not work, and with using docker's [config feature](https://docs.docker.com/engine/swarm/configs/) ro is the only option.

__Steps to reproduce:__
```sh
# Create the default config file
$ docker run --rm influxdb:2.0 influxd print-config > config.yml

# Start influxdb
$ docker run -p 8086:8086 \
      -v $PWD/config.yml:/etc/influxdb2/config.yml:ro \
      influxdb:2.0.4
```

__Expected behavior:__
The influxdb container should start.

__Actual behavior:__
```
chown: changing ownership of '/etc/influxdb2/config.yml': Read-only file system
```

**Comment by danxmoran** [comment]
Reproduced on my end 🤦 will update the docs

**Comment by Henkru** [comment]
Thanks to update.

If somebody else encounters this problem with the Docker swarm configs, the workaround is set the `uid` and `guid` of the config to `1000`.

The following example works.
```yml
version: '3.9'

services:
  influxdb:
    image: influxdb:2.0.4
    ports:
      - 8086:8086
    configs:
      - source: influxdb.config
        target: /etc/influxdb2/config.yml
        uid: '1000'
        gid: '1000'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

configs:
  influxdb.config:
    file: '<path to config>'

volumes:
  influxdb-storage:
  influxdb-config:
```
