### ISSUE TITLE
Can you provide a workable docker-compose file solution for InfluxdB and Telegraf

### ISSUE THREAD

**Issue by julia-hu-tm** [influxdata/influxdata-docker#494]
I tried with https://www.influxdata.com/blog/running-influxdb-2-0-and-telegraf-using-docker/

However it needs modification somewhere, I cannot figure out by myself, because I am very new to Influxdb. 

Can someone try this docker compose one more time, if there are parameters that require changes, at least label them as <Replace with your own parameter>

Thanks

**Comment by PrplHaz4** [comment]
It looks like the only things that changed between that blog post and the current instructions [here ](https://docs.influxdata.com/influxdb/v2.0/install/?t=Docker) are:
1. volume mount `influxdbv2` changed to `influxdb2`
2. image location `quay.io/influxdb/influxdb:v2.0.3` changed to just `influxdb:2.0` (should always get you latest of 2.0 branch)

Maybe something like this:
```
services:
  influxdb:
    image: influxdb:v2.0
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2:/.influxdb2
    ports:
      - "8086:8086"
# Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:v2.0
# Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
    entrypoint: influx setup --bucket mybucket -t mytoken -o myorg --username=myusername --password=passwordpasswordpassword --host=http://influxdb:8086 -f
      # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service. 
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb_cli
volumes:
  influxdb2:
```
