### ISSUE TITLE
Add support for Telegraf Docker container to use Telegraf configuration hosted in Influxdb2

### ISSUE THREAD

**Issue by derekpurdy** [influxdata/influxdata-docker#507]
The official docker container for telegraf should have support for a URL Location configuration file (i.e. telegraf --config http://192.168.1.5:8086/api/v2/telegrafs/XXXXXXXXXXXX) and INFLUX_TOKEN

**Comment by Olegt0rr** [comment]
The same question, how to run Docker / DockerCompose to pass cloud-hosted config?

<img width="719" alt="Screenshot 2021-07-14 at 18 33 51" src="https://user-images.githubusercontent.com/25399456/125650056-10f10542-4643-40c4-b47a-150527e09a53.png">

**Comment by edward3h** [comment]
This worked for me...

_.env_

```ini
INFLUX_TOKEN=xxxxx
TELEGRAF_CONFIG_URL=http://influxdb:8086/api/v2/telegrafs/xxxxx
```

_docker-compose.yml_

```yaml
version: "3.9"
services:
  telegraf:
    image: telegraf
    command: ["telegraf", "--config", $TELEGRAF_CONFIG_URL]
    env_file: .env
    networks: 
      - my_internal_network
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
```
