### ISSUE TITLE
Cannot Create Directory /root

### ISSUE THREAD

**Issue by GD-L** [influxdata/influxdata-docker#512]
I updated this stack with `docker-compose pull && docker-compose down && docker-compose up -d`, I've typically had no issues with this, but recently after bringing the container back up I receive the log error:
`mkdir: cannot create directory '/root': Permission denied`. Nothing new in the stack and it was working prior to my most recent pull. Can't change the log level to debug because it won't proceed past the root.

Compose Segment:
```
---
version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
      - "25826:25826/udp"   
    volumes:
      - /docker-volumes/data/TIG/influxdb2/data:/var/lib/influxdb2
      - /docker-volumes/data/TIG/influxdb2/config:/etc/influxdb2
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=upgrade
      - DOCKER_INFLUXDB_INIT_USERNAME=$USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=Home
      - DOCKER_INFLUXDB_INIT_BUCKET=Homelab_Stats
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    restart: unless-stopped
```
Docker Info:
```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
