### ISSUE TITLE
[inputs.ping] ping failed: permission changes required, enable CAP_NET_RAW capabilities

### ISSUE THREAD

**Issue by DocBrown101** [influxdata/influxdata-docker#560]
In a docker compose setup with the following configuration for the influx service I get the ping failed error:

```
version: "2.4"
services:
  telegraf:
    image: telegraf:1.20.4
    container_name: 7-telegraf
    restart: on-failure:5
    extra_hosts:
      - influxdb:192.168.0.220
    user: telegraf:998
    cpu_shares: 100
    pids_limit: 100
    mem_limit: 100m
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
```

Before the update that the container runs without root it worked.
I was hoping this would fix it: https://github.com/influxdata/influxdata-docker/pull/552

My used telegraf.conf
```
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  hostname = "192.168.0.220"
  omit_hostname = false

[[inputs.ping]]
interval = "60s"
urls = ["8.8.8.8", "amazon.de", "google.com", "github.com"]
count = 2
method = "native"
#method = "exec"
ping_interval = 1.0
timeout = 2.0
ipv6 = false
```
