### ISSUE TITLE
Why retention policy environment variable doesn't work?

### ISSUE THREAD

**Issue by agn-7** [influxdata/influxdata-docker#580]
I use _influxdb v1.7.11_ in a docker container. I read there is an env var in [hub.docker influxdb description](https://hub.docker.com/_/influxdb?tab=description) in order to set a retention policy on a database. However, it doesn't work!

> `DOCKER_INFLUXDB_INIT_RETENTION`: The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.

Here's a piece of my `docker-compose.yml`:

```
  influxdb:
    image: influxdb:1.7.11
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root
      - INFLUXDB_RETENTION_ENABLED=true
      - INFLUXDB_INIT_RETENTION=2h
      - DOCKER_INFLUXDB_INIT_RETENTION=2h
    volumes:
      - ./influxdb:/var/lib/influxdb
```
