### ISSUE TITLE
Cannot start influxdb in docker with letsencrypt

### ISSUE THREAD

**Issue by Igorgro** [influxdata/influxdata-docker#602]
Hello. I'm trying to start InfluxDB in docker using the letsencrypt certs from host. This is my compose file:
```yml
version: '3.6'
services:
  influxdb:
    image: influxdb:2.1.1
    ports:
      - 8086:8086
    volumes:
      - /opt/influxdb/data:/var/lib/influxdb2
      - /opt/influxdb/config.yml:/etc/influxdb2/config.yml
      - /etc/letsencrypt/live/example.com/cert.pem:/etc/letsencrypt/live/example.com/cert.crt:ro
      - /etc/letsencrypt/live/example.com/privkey.pem:/etc/letsencrypt/live/example.com/privkey.key:ro
```
I'm getting the following error:
```
influxdb-influxdb-1  | Error: open /etc/letsencrypt/live/example.com/privkey.key: permission denied
```

If I run the `whoami` command in the container by adding `command: whoami` to compose file, it gives the following output:
```
Attaching to influxdb-influxdb-1
influxdb-influxdb-1  | root
```
And this is the permissions of files (output of running `command: ls -l /etc/letsencrypt/live/example.com/privkey.key`):
```
influxdb-influxdb-1  | -rw------- 1 root root 1700 Apr  1 18:33 /etc/letsencrypt/live/example.com/privkey.key
```

Why can't influxdb open this file if it is run as root and the file is also owned by root?
