### ISSUE TITLE
Permission denied on temp config file in entrypoint

### ISSUE THREAD

**Issue by razaqq** [influxdata/influxdata-docker#644]
`/entrypoint.sh: line 303: /tmp/config.yml: Permission denied` and container restarts indefinitely

**Comment by powersj** [comment]
Hi,

Can you provide some more details, like what container image you are using? How you are launching that container? A docker file if applicable?

Thanks

**Comment by razaqq** [comment]
has nothing to do with the compose file but here it is anyways
the temp file is being created with wrong permissions, set the permissions in the entrypoint or smth

```
version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=pass
      - DOCKER_INFLUXDB_INIT_ORG=grafana
      - DOCKER_INFLUXDB_INIT_BUCKET=grafana
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=grafana
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
      - INFLUXD_CONFIG_PATH=/etc/influxdb2
    restart: always
```
