### ISSUE TITLE
Docker fails with permission error (since version 1.19)

### ISSUE THREAD

**Issue by severindellsperger** [influxdata/influxdata-docker#659]
Hi all,

I wanted to use telegraf within a docker-compose file and run into the following issue:
Telegraf exited immediately with the following logs:
```
su-exec: telegraf: Operation not permitted
```

Here is the service definition used in the docker-compose.yml:
```
  telegraf:
    image: telegraf:1.25-alpine
    ports:
      - '32400:32400'
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - "../telegraf/telegraf-pt-sample.conf:/etc/telegraf/telegraf.conf:ro"
```

I found out, that I run into the same error using version 1.19+.
So, 1.18 was the last version that worked.
Also, I found out that it worked using a user or running the container in privileged mode:
```
# does not work
docker run  --rm  -v $PWD/telegraf-pt-sample.conf:/etc/telegraf/telegraf.conf:ro telegraf

# work with user telegraf
 docker run -u telegraf  --rm  -v $PWD/telegraf-pt-sample.conf:/etc/telegraf/telegraf.conf:ro telegraf

# work in privileged mode
docker run --privileged --rm  -v $PWD/telegraf-pt-sample.conf:/etc/telegraf/telegraf.conf:ro telegraf
```

So, I solved the problem add the `USER` info to my docker-compose file:
```
  telegraf:
    image: telegraf:1.25-alpine
    ports:
      - '32400:32400'
    user: telegraf
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - "../telegraf/telegraf-pt-sample.conf:/etc/telegraf/telegraf.conf:ro"
```

Anyway, according to [the documentation](https://hub.docker.com/_/telegraf) it should work without defining the user.
Maybe it would be better anyway to use the [USER instruction](https://docs.docker.com/engine/reference/builder/#user) in the Dockerfile itself. 
I can do a PR if this is desired.
