### ISSUE TITLE
Env configurations not recognized in lastest tagged image?

### ISSUE THREAD

**Issue by jormc** [influxdata/influxdata-docker#686]
Hi there,

I'm using **_influxdb:latest_** and **_influxdb:alpine_** images in my docker compose, but it doesn't recognizes the ENV_VARS. Only with 2.0 version tag are recognized them.

Is it a bug or an issue with latest docker image versions? Are I doing something wrong?

This is my docker compose service:

```
services:

  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    env_file:
      - ./env/influxdb2.env
    volumes:
      - ./data/influxdb2:/var/lib/influxdb2
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    networks:
      - influxdb
  
networks:
  influxdb:
```

An this my env file:

```
DOCKER_INFLUXDB_INIT_MODE=setup
DOCKER_INFLUXDB_INIT_USERNAME=admin
DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
DOCKER_INFLUXDB_INIT_ORG=my-org
DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
```

When I start the instance, always shows me the initial config page, but i 2.0 versio it is ok.

Thanks!
