### ISSUE TITLE
Telegraf docker entrypoint script change needed to support deployment from compose script

### ISSUE THREAD

**Issue by wz2b** [influxdata/influxdata-docker#734]
Referencing #724 and #543 I was still having problems with a specific line in the [entrypoint script](https://github.com/influxdata/influxdata-docker/blob/0f0bdbbb22b44e9a5953b0f733d6992ade4d7c55/telegraf/1.30/entrypoint.sh#L21)

The line currently reads:

`extra_groups="$(id -Gn || true)"`

This script doesn't honor UID; rather, if the UID is 0 (root) it just executes as the 'telegraf' user.  Unfortunately, if you are root, that id will get the groups associated with root, not telegraf.  I think it needs to be changed to:

`extra_groups="$(id -Gn telegraf || true)"`

With this change, I can specify a service in a compose file:

```
services: 
  telegraf:
    image: mystack/telegraf
    container_name: telegraf
    volumes: 
      - type: bind
        source: /etc/telegraf
        target: /etc/telegraf
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    build:
      context: telegraf
```

and a Dockerfile that does this:

FROM docker.io/telegraf
RUN groupadd -r docker -g 122
RUN usermod -aG docker telegraf
COPY custom-entrypoint.sh /custom-entrypoint.sh
RUN chmod +x /custom-entrypoint.sh
ENTRYPOINT ["/custom-entrypoint.sh"]
CMD ["telegraf"]
