### ISSUE TITLE
Add way to create CQs and databases on container creating

### ISSUE THREAD

**Issue by Disminder** [influxdata/influxdata-docker#75]
Just take a look at "Initializing a fresh instance" section in [MySQL](https://hub.docker.com/_/mysql/) Docker image. It would be awesome, if we can run .sh script or InfluxQL file on creating.

**Comment by bryanburgers** [comment]
Currently my docker-compose.yml has to look something like this in order to be able to successfully use influx in a docker-compose environment.

```
services:
  influxdb:
    image: influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
  
  influxdb_create_instance:
    image: tutum/curl
    command: /bin/sh -c 'sleep 2 && curl -X POST -G http://influxdb:8086/query --data-urlencode "q=CREATE DATABASE metrics"'
```

This is not ideal because (a) it involves an extra docker container, which clutters up the docker-compose file and has to run every time `docker-compose up` is run, and (b) sleeps for an arbitrary amount of time to try to wait until influxdb is ready, which could fail due to variability in how long influx takes to start.

Compare that to MySQL, which can create a database right from the image

```
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: metrics
```

or in a pinch, can even specify custom commands to run when the database is ready.

```
services:
  mysql:
    image: mysql   
    environment:
      MYSQL_DATABASE: metrics
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
```

**Comment by jsternberg** [comment]
This feature exists now. I just need to document it. It was merged in #131.

**Comment by bryanburgers** [comment]
Yay! Thanks!

I can confirm that this now works:

```
services:
  influxdb:
    image: influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: metrics
```
