### ISSUE TITLE
Document DOCKER_INFLUXDB_INIT_USERNAME_FILE, DOCKER_INFLUXDB_INIT_PASSWORD_FILE, DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/influxdata-docker#763]
In the `influxdb` image documentation, add the following environment variables and how to use them with Compose `secrets`:

```yaml
DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin 
DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-pwd 
DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
```
