### ISSUE TITLE
how to set env  for core through docker compose

### ISSUE THREAD

**Issue by criticalboot** [influxdata/influxdata-docker#798]
Unable to run  through Docker Compose with 

```
influxdb:
    image: influxdb:core
    restart: unless-stopped
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    volumes:
      - $PWD/influx/scripts:/docker-entrypoint-initdb.d
      - influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_HOSTNAME=${INFLUXDB_HOSTNAME}
```

error  got on log is 

```
For more information, try '--help'.
error: the following required arguments were not provided:
  --node-id <NODE_IDENTIFIER_PREFIX>

Usage: influxdb3 serve --node-id <NODE_IDENTIFIER_PREFIX> --log-filter <LOG_FILTER> --plugin-dir <PLUGIN_DIR>
```

Am I missing some thing here 
or
missing documentation to passing these env <NODE_IDENTIFIER_PREFIX>, <LOG_FILTER> and <PLUGIN_DIR>
