### ISSUE TITLE
chronograf container influx link failure

### ISSUE THREAD

**Issue by mcandre** [influxdata/influxdata-docker#86]
I'm trying to configure chronograf to point to influxdb via docker-compose, but when I open chronograf in my browser, it still prompts for influxdb connection details. Am I doing something wrong?

```yaml
version: "2"
services:
  telegraf:
    image: "telegraf-compose:1.2"
    links:
      - influxdb
    ports:
      - "8125:8125/udp"
  influxdb:
    image: "influxdb:1.2"
    ports:
      - "8086:8086"
  chronograf:
    image: "chronograf:1.2beta"
    links:
      - influxdb
    ports:
      - "8888:8888"
  kapacitor:
    image: "kapacitor:1.2"
    links:
      - influxdb
    ports:
      - "9092:9092"
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: "http://influxdb:8086"
```

(The telegraf-compose:1.2 and chronograf:1.2beta images are technically custom images, built similarly to the official ones in order to fill gaps in the Docker Compose experience for the TICK stack, like defaulting the influxdb address from `localhost` to `influxdb` for chronograf.)
